### PR TITLE
Add aarch64 FP16 backend

### PR DESCRIPTION
**Pull request by Bhavana-Kilambi**
This patch adds aarch64 backend for the FP16 operations added by Jatin which will be merged with JDK24.

### CODE REVIEW

**Comment by Bhavana-Kilambi** [comment]
Hi @jatin-bhateja , I added aarch64 backend for the FP16 operations. Could you please review (as I made some non-aarch64 changes as well)? Thanks!

**Comment by Bhavana-Kilambi** [comment]
Hi @jatin-bhateja , can you please review this patch and add to your patch which adds initial FP16 support for JDK-24? Thanks!

**Comment by jatin-bhateja** [comment]
Hi @Bhavana-Kilambi , Kindly rebase the patch over the latest version of my patch. It will help if you can also regress the integrated patch over the newly added Float16 tests on the AARCH64 target.

**Comment by Bhavana-Kilambi** [comment]
Sure, I will thanks!

**Comment by jatin-bhateja** [comment]
Hi @Bhavana-Kilambi , Can you kindly rebase this patch with latest changes.

**Comment by Bhavana-Kilambi** [comment]
Hi Jatin, yes I am working on it.

**Pull request closed without merging**
